<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <OutputPath>..\bin\Client\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Platforms>x64</Platforms>
    <Configurations>Debug2022;Debug2023;Debug2024;Debug2025;Release2022;Release2023;Release2024;Release2025</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug2025' Or '$(Configuration)'=='Release2025'">
    <TargetFramework>net8.0-windows8.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug2024' Or '$(Configuration)'=='Release2024'">
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug2023' Or '$(Configuration)'=='Release2023'">
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug2022' Or '$(Configuration)'=='Release2022'">
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationIcon>Testing.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\AssemblyInfo\AssemblyInfo.Global.cs">
      <Link>Properties\AssemblyInfo.Global.cs</Link>
    </Compile>
    <Compile Include="..\AssemblyInfo\AssemblyInfo.Version.cs">
      <Link>Properties\AssemblyInfo.Version.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Testing.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Revit.TestRunner.Shared\Revit.TestRunner.Shared.csproj" />
  </ItemGroup>
</Project>